### ISSUE TITLE
Connection error with mqtt cert

### ISSUE THREAD

**Issue by samerhijazi** [pmalhaire/xk6-mqtt#11] opened 2022-08-03 18:52 UTC
Hi,
i am trying to make connection with cert with the following setting and i get "connection error". Is there a way to debug. Or do i do it wrong.

It does work for a local HivemQ without cert.

Thanks
Samer

![image](https://user-images.githubusercontent.com/11427019/182686171-744c557a-0a01-4fe3-956d-e47774fd74aa.png)

**Comment by pmalhaire** [comment] 2022-08-05 06:22
Hello,
What is the error you are getting ?

The code for this part is in client.go

**Comment by samerhijazi** [comment] 2022-08-05 15:55
Hello,

the problem is with cert. But the file is correct.

![image](https://user-images.githubusercontent.com/11427019/183114318-e0076fc0-0736-4311-ad47-2e9aad5c0fd0.png)

**Comment by pmalhaire** [comment] 2022-10-02 11:00
Hi, I fixed it and pushed the fix on the main branch.

**Closed** 2022-10-02 11:16 UTC

**Comment by alvinjoseph7** [comment] 2023-11-13 20:32
Hi, I'm facing a similar publish connect error when trying to publish to a mosquitto broker(mosquitto version 1.4.15) with my self-signed certificate. Publish to the 1883 port works well, but connection to port 8883 is causing this issue.

![image](https://github.com/pmalhaire/xk6-mqtt/assets/73344061/fc470cc3-0d1c-45a5-b3a8-695a0c08394c)



Mosquitto logs:
![image](https://github.com/pmalhaire/xk6-mqtt/assets/73344061/cbeaada8-7a63-4815-adf7-e1cd11d86d10)

I am pretty that I am using the correct CA certificate file(.pem format) in my script to authenticate because when I use the `mosquitto_pub`  tool with the same CA cert, I am able to connect to the broker(8883 port).

**Comment by pmalhaire** [comment] 2023-11-13 22:08
@alvinjoseph7 maybe you can reproduce It with more details. The CI is testing this, so it's working, not that TLS 1.3 Is enforced.

**Comment by alvinjoseph7** [comment] 2023-11-18 01:12
Hi, I was able to fix the issue. The problem was with the self-signed certificates I was using. 
This link finally helped me out: http://www.steves-internet-guide.com/mosquitto-tls/
